import os
import glob

release_folder_name    = "release/"
developer_folder_pre = "dev_"


for filepath1 in glob.iglob('*'):
    if not filepath1.lower().endswith(".py"):
        for filepath2 in glob.iglob(filepath1+"/*"):
            if filepath2.lower().endswith(".html"):
                print("REMOVEING: "+filepath2)
                os.remove(filepath2)

print('\n\n\n')

def make_html( filepath ):
    file_name = filepath.split("/")[-1]
    
    if (file_name == "EMU.js"):
        return
    
    folder_name = release_folder_name
    if ( file_name[3] == "_" and file_name[0:3].isdigit() ):
        folder_name = developer_folder_pre+file_name[0:3]+"/"
        file_name = file_name[4:len(file_name)]
    
    html_name = file_name.replace(".js",".html")
    
    title_words = file_name.replace(".js","").split("_")
    new = []
    for word in title_words:
        if not( word in ['the','and','no'] ):
            word = word.capitalize()
        new.append(word)
    
    title = ' '.join(new)
    
    print("CREATEING: "+folder_name+html_name)
    
    return [ folder_name, html_name,'''
<!-- his page was automatically generated by "build_frontends.py" -->

<!doctype html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>'''+title+'''</title>
    <link href="../../css/style.css" rel="stylesheet" />
    <script type="module" src="../../libs/RomBootLoader/jszip.js"></script>
    <script type="module" src="../../libs/RomBootLoader/jszip-utils.min.js"></script>
    <script type="module" src="../../libs/RomBootLoader/RomBootLoader.js"></script>
  </head>
  <body>
    <script type="module" src="../'''+filepath+'''"></script><canvas id="canvas"></canvas>
    <script>
      const audioCtx = 'AudioContext' in window && new window.AudioContext() || 'webkitAudioContext' in window && new window.webkitAudioContext();
      const canvas = document.getElementById('canvas');
    </script>
  </body>
</html>''']


for filepath in glob.iglob('../drivers/*.js'):
    if filepath.endswith(".js"):
        data = make_html( filepath )
        if (data):
            if not os.path.exists(data[0]):
                os.makedirs(data[0])
            with open(data[0]+data[1], 'w') as f:
                f.write(data[2])



print('\nALL DONE!')



